spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #表明gateway开启服务注册和发现的功能，
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
          # 这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true #???????????????
      routes:
        #我们自定义的路由 ID，保持唯一
        - id: user-service
          #目标服务器地址，表示从微服务注册中心（如Eureka）订阅user-service服务，并且进行服务的路由。
          uri: lb://user-service
          #路由条件，接收一个输入参数，返回一个布尔值结果。
          predicates:
            - Path=/api/user/**
          #过滤规则
          filters:
            - StripPrefix=1
    #- StripPrefix=1表示路由（转发）时会去掉/user
  #- StripPrefix后面的数字是几表示去除几层路径
  #例如写2的话就会去除/api/user
  #即访问/api/user/getUser会变为/user/getUser
  #上面的路由配置表示所有包含/api/user/的url都会被路由(转发)到user-service服务
  #例如访问http://localhost:8088/api/user/getUser会转发到http://localhost:8090/user/getUser
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


