spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #??????Eureka Server??????????Eureka Server???false
    fetch-registry: false         #?????? Eureka ?????????????  ??
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
